import React from 'react'; // Add import statement for React
import type { Metadata } from 'next';

import '@/styles/index.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = (
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }> // Change function component to arrow function
) => (
  <html lang="en">
    <body>{children}</body>
  </html>
);
export default RootLayout;
